{{type}} {
    orientation   : {{orientation}},
    alignChildren : {{alignChildren}},
    preferredSize : [{{width}}, {{height}}],
    text          : {{text}},
    margins       : {{margins}},

    graphics       : {{graphics}},
    visible        : {{visible}},
    bounds         : {{bounds}},
    frameBounds    : [{{frameBoundsX1}}, {{frameBoundsY1}}, {{frameBoundsX2}}, {{frameBoundsY2}}],
    frameLocation  : [{{frameLocationX}}, {{frameLocationY}}],
    frameSize      : [{{frameSizeWidth}}, {{frameSizeHeight}}],
    location       : {{location}},
    maximumSize    : [{{maximumSizeWidth}},   {{maximumSizeHeight}}],
    minimumSize    : [{{minimumSizeWidth}},   {{minimumSizeHeight}}],
    preferredSize  : [{{preferredSizeWidth}}, {{preferredSizeHeight}}],
    size           : [{{sizeWidth}}, {{sizeHeight}}],
    windowBounds   : [{{windowBoundsX1}}, {{windowBoundsY1}}, {{windowBoundsX2}}, {{windowBoundsY2}}],
    characters     : {{characters}},
    justify        : '{{justify}}',
    text           : '{{text}}',
    active         : {{active}},
    shortcutKey    : '{{shortcutKey}}',
    cancelElement  : {{cancelElement}},
    defaultElement : {{defaultElement}},
    maximized      : {{maximized}},
    minimized      : {{minimized}},
    alignChildren  : '{{alignChildren}}',
    margins        : {{margins}},
    spacing        : {{spacing}},
    indent         : {{indent}},
    orientation    : '{{orientation}}',
    alignment      : '{{alignment}}',
    enabled        : {{enabled}},
    helpTip        : '{{helpTip}}',
    opacity        : {{opacity}},

    children       : '{{children}}'
}
